enum Årsaker {
    GRADERT_MOT_TILSYN = 'GRADERT_MOT_TILSYN',
    AVKORTET_MOT_INNTEKT = 'AVKORTET_MOT_INNTEKT',
    AVKORTET_MOT_SØKERS_ØNSKE = 'AVKORTET_MOT_SØKERS_ØNSKE',
    OPPFYLT_PGA_BARNETS_DØDSFALL = 'OPPFYLT_PGA_BARNETS_DØDSFALL',
    FULL_DEKNING = 'FULL_DEKNING',
}

export default Årsaker;
