enum Årsaker {
    // Oppfylt årsaker
    GRADERT_MOT_TILSYN = 'GRADERT_MOT_TILSYN',
    AVKORTET_MOT_INNTEKT = 'AVKORTET_MOT_INNTEKT',
    AVKORTET_MOT_SØKERS_ØNSKE = 'AVKORTET_MOT_SØKERS_ØNSKE',
    OPPFYLT_PGA_BARNETS_DØDSFALL = 'OPPFYLT_PGA_BARNETS_DØDSFALL',
    FULL_DEKNING = 'FULL_DEKNING',

    // Ikke oppfylt årsaker
    UTENOM_PLEIEBEHOV = 'UTENOM_PLEIEBEHOV',
    FOR_LAV_GRAD = 'FOR_LAV_GRAD',
    FOR_HØY_TILSYNSGRAD = 'FOR_HØY_TILSYNSGRAD',
    LOVBESTEMT_FERIE = 'LOVBESTEMT_FERIE',
    BARNETS_DØDSFALL = 'BARNETS_DØDSFALL',
    INNGANGSVILKÅR_IKKE_OPPFYLT = 'INNGANGSVILKÅR_IKKE_OPPFYLT',
}

export default Årsaker;
